### ISSUE TITLE
Determine cause of occasional debugging exception in UiDispatcherService

### ISSUE THREAD

**Issue by atwoosnam** [vmware-tanzu/tanzu-toolkit-for-visual-studio#101]
Sometimes when closing the experimental instance of Visual Studio (VSIX debugging environment), this exception will be displayed:

![image.png](https://images.zenhubusercontent.com/5f6e427c72f8abbfafb30775/8a62ba49-8c01-4d90-8e30-acfcb4c757f5)

This has happened a handful of times since introducing the background polling feature (#16), but it has never appeared to impact the actual function of the VS extension; it only ever appears after the experimental instance of VS has been shut down.

Let's be sure the cause of this exception doesn't have any negative implications for the health/performance of the VS extension (e.g. when this extension is used in the wild, all threads should be cleaned up nicely whenever VS is shut down)

**Comment by jkonicki** [comment]
Likely an issue with debugging and the task canceling prior to executing command.
