### ISSUE TITLE
Renaming of Tanzu to be more specific to TAS

### ISSUE THREAD

**Issue by jkonicki** [vmware-tanzu/tanzu-toolkit-for-visual-studio#109]
There are some areas of the extension that need to be renamed.  

Feedback is welcome:
- From Tanzu Cloud Explorer -> Tanzu Application Service (optional "Explorer") --- Not sure if adding Explorer is necessary, but we can see how it fits since the name will be very long.  I also don't want to use acronyms so TAS is out, IMO.
- Output window :  Tanzu Output -> Tanzu Application Service Output
- Other areas that are generic to "Tanzu" should also be listed here.

**Comment by atwoosnam** [comment]
+1 on acronym avoidance! 
What if we were to leave "Explorer" out of the tool window title (I agree that it's not necessary there & might make the title too long) but leave it in the menu command title?  (example screenshot of what that would look like below)

![image](https://user-images.githubusercontent.com/22666145/126001075-f3b43dfd-fa7d-40f8-ae65-d1cc5f4deb11.png)

**Comment by colsonrice** [comment]
I would leave in "Explorer". It looks like there should be enough space to fit in the full title in most cases. I think it's worth leaving in for the additional context it'd give the user.

**Comment by colsonrice** [comment]
Do we have a pattern for if the title is too long? Would it be cutoff with an ellipsis?
