### ISSUE TITLE
Persist TAS connection after closing Visual Studio

### ISSUE THREAD

**Issue by atwoosnam** [vmware-tanzu/tanzu-toolkit-for-visual-studio#110]
Users of the Tanzu Toolkit for Visual Studio extension should not have to log into TAS again each time they close & re-open Visual Studio.

**Comment by jkonicki** [comment]
This will likely be covered under the profile options #120

**Comment by atwoosnam** [comment]
[DTE2.Globals](https://docs.microsoft.com/en-us/dotnet/api/envdte.globals?view=visualstudiosdk-2022) hasn't been working as a viable option for me (I've tried everything I can think of to get it to work & the values just aren't persisting between VS sessions)

**Comment by atwoosnam** [comment]
This might be a good workaround! https://www.vsixcookbook.com/recipes/settings-and-options.html
