### ISSUE TITLE
Decrease time-to-deploy for .NET Core apps

### ISSUE THREAD

**Issue by atwoosnam** [vmware-tanzu/tanzu-toolkit-for-visual-studio#113]
Specifying the buildpack to use when deploying an app seems to significantly decrease the amount of time the `cf push` command takes to complete (this is probably because without adding `-b`, the `cf push` process spends a good amount of time downloading ALL available buildpacks to increase the likelihood that one of them will match the app framework).

**Comment by jkonicki** [comment]
Consider a way to specify the buildpacks on deploy. It might just be adding them to manifest file.

**Comment by TimHess** [comment]
Buildpacks can be specified during deployment now
