### ISSUE TITLE
Research the ability to leverage VS Publish Wizard window

### ISSUE THREAD

**Issue by jkonicki** [vmware-tanzu/tanzu-toolkit-for-visual-studio#118]
Investigate the feasibility of adding a custom "TAS" deployment option to the native VS "Publish" wizard.

(This ticket used to encompass work around publishing apps from binaries as opposed to from source -- that work is now encapsulated in #151)
~Currently, we are able to `cf push` from source.  We need to add the ability to push binaries.  ~
~From discussions, this is likely the recommended way for our customers as all the dependencies and artifacts are bundled as expected and removes possible issues when deploying from source. ~

**Comment by atwoosnam** [comment]
The [Cloud Foundry docs](https://docs.cloudfoundry.org/buildpacks/binary/index.html) have some advice on how to push .NET Core apps to a Windows host:

> **.NET Core on Windows**
> 
> To run .NET Core apps on the Windows stack, you must use the Binary buildpack. Follow the steps below to configure your Cloud Foundry manifest appropriately.
> 
> 1. In the app manifest file, specify the windows stack and a custom start command. This file should be in the same folder as your .csproj file and be marked copy always.
> 
>```
 ---
> applications:
> - name: MY-AWESOME-APP
>   stack: windows
>   command: cmd /c .\MY-AWESOME-APP --urls=http://0.0.0.0:%PORT%
```
> 2. Publish the project using the dotnet CLI or Visual Studio.
> 
> `$ dotnet publish -o ./publish -r win10-x64 -f netcoreapp2.1`
>
> 3. A publish folder should now exist. Navigate to this publish folder and verify the manifest.yml file exists. Run cf push to deploy your app.
> 
> ```
$ cd publish
> $ cf push MY-AWESOME-APP
```

**Comment by atwoosnam** [comment]
The docs seem to recommend the following deployment strategies:

|Type of .NET App |Buildpack |
|--- |--- |
|.NET Console (not recommended to run on CF; see _footnote_) |[Binary](https://docs.cloudfoundry.org/buildpacks/binary/index.html)|
|.NET Core pushed to Linux stack |[.NET Core](https://docs.cloudfoundry.org/buildpacks/dotnet-core/index.html)|
|.NET Core pushed to Windows stack |[Binary](https://docs.cloudfoundry.org/buildpacks/binary/index.html)|
|ASP.NET MVC| [HWC](https://docs.cloudfoundry.org/buildpacks/hwc/index.html)|
|ASP.NET Web Forms| [HWC](https://docs.cloudfoundry.org/buildpacks/hwc/index.html)|
|ASP.NET WebAPI Apps| [HWC](https://docs.cloudfoundry.org/buildpacks/hwc/index.html)|
|Windows Communication Foundation (WCF)| [HWC](https://docs.cloudfoundry.org/buildpacks/hwc/index.html)|

_Footnote_:

> Console apps are not recommended to run on Cloud Foundry because they do not normally run as a single instance and are not highly available. If you need to run a console app on Cloud Foundry, see Console Applications in the .NET Cookbook.

**Comment by zzori-theoriginal** [comment]
Possible Useful Articles:

- https://docs.cloudfoundry.org/buildpacks/binary/index.html

- https://docs.cloudfoundry.org/devguide/deploy-apps/deploy-app.html

- https://github.com/cloudfoundry/binary-buildpack

-

**Comment by atwoosnam** [comment]
The VS "Publish" window doesn't seem to be readily extensible (@atwoosnam, @zzori-theoriginal and @dtillman all looked & couldn't find a way)

**Comment by jkonicki** [comment]
The team will continue investigating this option and reach out through MSFT channels to see if this is even an option.

**Comment by atwoosnam** [comment]
@dtillman has reached out to Mads Kristensen about the possibility of integrating into the Publish wizard -- no response yet

**Comment by atwoosnam** [comment]
Iceboxing for now until we hear back from Mads

**Comment by jkonicki** [comment]
Related to #11.

**Comment by dtillman** [comment]
Issue related to asking question to Mads K: https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/issues/166
