### ISSUE TITLE
Add ability to identify a "production" environment

### ISSUE THREAD

**Issue by jkonicki** [vmware-tanzu/tanzu-toolkit-for-visual-studio#121]
Provide some way to flag any deployments to a production environment. 

Some options:
* Require a separate confirmation to ensure they want to deploy to production. 
* Force users to select a check box before deployment is allowed

**Comment by TimHess** [comment]
Current view is that environment access should be controlled by corporate policy rather than a feature in this extension. Deployment profiles should alleviate concerns in this regard by providing an option to appropriately name a deployment target
