### ISSUE TITLE
Update the current extension icons.

### ISSUE THREAD

**Issue by jkonicki** [vmware-tanzu/tanzu-toolkit-for-visual-studio#122]
New icons have been cleaned up and created.  They need to be updated in the extension

**Comment by zzori-theoriginal** [comment]
Colson made Light and Dark icons and we're trying to see which can be used across all themes, since our current implementation doesn't allow for icon switches based on theme. Here's what a dark and light icon look like together, on two different themes.

![newiconsdark.PNG](https://images.zenhubusercontent.com/5f86121f98b4ad21fcd4f604/838104c9-29bd-4edc-a54c-d033e1b09ea4)
![newiconlight.PNG](https://images.zenhubusercontent.com/5f86121f98b4ad21fcd4f604/1c2a118f-5316-45b3-9f7f-8c37b2f4d8c8)

**Comment by zzori-theoriginal** [comment]
Here's how it looks with both light icons:
![lighticonsdark.PNG](https://images.zenhubusercontent.com/5f86121f98b4ad21fcd4f604/490e15e4-e83f-4a30-a178-1062d15be59b)
![lighticonslight.PNG](https://images.zenhubusercontent.com/5f86121f98b4ad21fcd4f604/4e7491bf-e649-4307-a7b6-a2d4b4b6ef76)

**Comment by zzori-theoriginal** [comment]
Here's how it looks with both dark icons:
![bothdarkiconsdark.PNG](https://images.zenhubusercontent.com/5f86121f98b4ad21fcd4f604/aeef9a8b-6f0f-486f-b8ed-1ebf286ebb2e)
![bothdarkiconslight.PNG](https://images.zenhubusercontent.com/5f86121f98b4ad21fcd4f604/fc358c8c-fa5a-4a3b-8f6d-09f91788b8fc)

**Comment by zzori-theoriginal** [comment]
New icons provided by Colson look crisper and work with all themes; only possible hang up is that the Tanzu logo is missing the green color/section.

![newicondarktheme830.PNG](https://images.zenhubusercontent.com/5f86121f98b4ad21fcd4f604/adb5981b-0c13-4152-a593-34996df84303)
![newiconsblueextracontrasttheme830.PNG](https://images.zenhubusercontent.com/5f86121f98b4ad21fcd4f604/2083f191-be91-4581-bb9b-51377bb6daaf)
![newiconsbluetheme830.PNG](https://images.zenhubusercontent.com/5f86121f98b4ad21fcd4f604/4cf32338-2927-4008-9e1c-eee009a42555)
![newiconslighttheme830.PNG](https://images.zenhubusercontent.com/5f86121f98b4ad21fcd4f604/d29e25ee-30de-49bd-988d-e5bbf0e88be8)

**Comment by atwoosnam** [comment]
#### Current deployment icon in dark mode:
![image.png](https://images.zenhubusercontent.com/5f6e427c72f8abbfafb30775/ba149fe4-cb42-4f4a-8b97-6b8ee797705c)

#### New deployment icon in dark mode:
![image.png](https://images.zenhubusercontent.com/5f6e427c72f8abbfafb30775/1707d5c9-f315-459e-8644-593840bc468b)

**Comment by atwoosnam** [comment]
#### Current tree view icons in dark mode:
![image.png](https://images.zenhubusercontent.com/5f6e427c72f8abbfafb30775/73a80aec-b51c-4248-92b4-cf6e0869824a)

#### New tree view icons in dark mode:
![image.png](https://images.zenhubusercontent.com/5f6e427c72f8abbfafb30775/d279ea06-ad6d-454d-9bdc-56c61d4b752f)

**Comment by atwoosnam** [comment]
New TAS icon in tree view:
![image.png](https://images.zenhubusercontent.com/5f6e427c72f8abbfafb30775/4ac88d1b-2a04-44c6-9350-f4548c1ab964)
