### ISSUE TITLE
Add Window tabs for tailing of logs

### ISSUE THREAD

**Issue by jkonicki** [vmware-tanzu/tanzu-toolkit-for-visual-studio#129]
As a user, when I select an application and choose to "Tail logs" option, I would like to have a new "Log Output" window or a new tab in the "Log Output" window created.  This would allow me the ability to view the tailing output of each of the applications at the same time and possible on different windows.

**Comment by atwoosnam** [comment]
https://docs.microsoft.com/en-us/visualstudio/extensibility/extending-the-output-window?view=vs-2022

**Comment by zzori-theoriginal** [comment]
research:

- can xaml windows be opened an infinite amount of times separately?

- if not, can we open them a limited amount of times, still separately?

**Comment by zzori-theoriginal** [comment]
unique id to track output windows for the different apps? window manager of some sort?

**Comment by zzori-theoriginal** [comment]
ViewLocatorService might just need a list of Output windows to keep track of?

**Comment by zzori-theoriginal** [comment]
2nd concern is how to manage the log stream

**Comment by zzori-theoriginal** [comment]
expected func for switching between log types: exit current flow in code behind, clear window, and then change log type
