### ISSUE TITLE
Build log tailing functionality 

### ISSUE THREAD

**Issue by jkonicki** [vmware-tanzu/tanzu-toolkit-for-visual-studio#131]
Implement a solution for tailing our logs per application.

**Comment by atwoosnam** [comment]
https://docs.microsoft.com/en-us/visualstudio/extensibility/extending-the-output-window?view=vs-2022

**Comment by zzori-theoriginal** [comment]
- having multiple output windows using the native tool window func

- having the app name in the title of the output window

- having clear button

- having a toggle for tailing logs (look at word wrap for ref)

- horizontal scroll instead of text wrap

**Comment by zzori-theoriginal** [comment]
we are using the `--recent` flag for the log functionality currently

**Comment by zzori-theoriginal** [comment]
- managing starting, stopping, and somehow resuming tailing logs

- also adding new button for tailing - keeping recent logs func

**Comment by atwoosnam** [comment]
Looks like when you use the CF CLI to tail app logs, it queries the same endpoint continuously looking for new lines of log output:
([sample logs output](https://app.zenhub.com/files/327998348/5b813ab6-3240-4e35-8d3f-3ea26ab23131/download))
![tail-app-logs-research.gif](https://images.zenhubusercontent.com/5f6e427c72f8abbfafb30775/4bd5eaed-94ef-4c07-8220-21e2835a8701)

**Comment by atwoosnam** [comment]
Found a promising piece of documentation: https://docs.microsoft.com/en-us/visualstudio/extensibility/creating-a-multi-instance-tool-window?view=vs-2019
