### ISSUE TITLE
Publish binaries to TAS

### ISSUE THREAD

**Issue by jkonicki** [vmware-tanzu/tanzu-toolkit-for-visual-studio#136]
We need to provide the ability to publish applications as compiled binaries.  

Currently, there is a Publish option available in VS.  Can we leverage this UI and add a TAS option or do we need to create our own "Publish to Tanzu Application Service" option?

**Comment by atwoosnam** [comment]
The docs seem to recommend the following deployment strategies:

|Type of .NET App |Buildpack |
|--- |--- |
|.NET Core pushed to Linux stack |[.NET Core](https://docs.cloudfoundry.org/buildpacks/dotnet-core/index.html)|
|.NET Core pushed to Windows stack |[Binary](https://docs.cloudfoundry.org/buildpacks/binary/index.html)|
|.NET Console (not recommended to run on CF; see _footnote_) |[Binary](https://docs.cloudfoundry.org/buildpacks/binary/index.html)|
|ASP.NET MVC| [HWC](https://docs.cloudfoundry.org/buildpacks/hwc/index.html)|
|ASP.NET Web Forms| [HWC](https://docs.cloudfoundry.org/buildpacks/hwc/index.html)|
|ASP.NET WebAPI Apps| [HWC](https://docs.cloudfoundry.org/buildpacks/hwc/index.html)|
|Windows Communication Foundation (WCF)| [HWC](https://docs.cloudfoundry.org/buildpacks/hwc/index.html)|

_Footnote_:

> Console apps are not recommended to run on Cloud Foundry because they do not normally run as a single instance and are not highly available. If you need to run a console app on Cloud Foundry, see Console Applications in the .NET Cookbook.

**Comment by atwoosnam** [comment]
@zzori-theoriginal made this comment on a different ticket -- reposting here so it doesn't get lost!

>Possible Useful Articles:
>
>- https://docs.cloudfoundry.org/buildpacks/binary/index.html
>- https://docs.cloudfoundry.org/devguide/deploy-apps/deploy-app.html
>- https://github.com/cloudfoundry/binary-buildpack

**Comment by zzori-theoriginal** [comment]
Helpful Articles:

- https://tanzu.vmware.com/content/blog/run-your-legacy-net-in-the-cloud-with-tanzu

- https://docs.pivotal.io/application-service-windows/2-9/using.html

- https://docs.pivotal.io/application-service/2-9/buildpacks/binary/index.html

- https://dotnet-cookbook.apps.pcfone.io/headless/console_app/

- https://docs.pivotal.io/application-service/2-9/buildpacks/hwc/index.html

- https://docs.pivotal.io/application-service-windows/2-9/develop.html

**Comment by atwoosnam** [comment]
We may want to leave it up to the user to select a "Runtime Identifier" to use with the `dotnet publish` command... I think this should line up with whatever is running in Cloud Foundry?

**Comment by atwoosnam** [comment]
We've been able to publish a `dotnet new webapi` app from binaries by following these steps:

1. `dotnet new webapi -n my-app`
2. `cd my-app`
3. `dotnet publish -o ./publish -r win-x64 -f net5.0` 
    - ^ the target framework moniker at the end of this command should match the `<TargetFramework>` value in the app's `.csproj` file
4. `vim manifest.yml`
```
---
applications:
- name: dotnet-new-webapi-9-15
  stack: windows
  command: cmd /c .\dotnet-new-webapi-9-15 --urls=http://*:%PORT%
  health-check-type: http
  buildpacks:
  - binary_buildpack
```
5. `cd publish`
6. `cf push -f ../manifest.yml`

**Comment by atwoosnam** [comment]
Important consideration: `dotnet publish` may not work for full-framework apps
