### ISSUE TITLE
Add a confirmation dialog for delete

### ISSUE THREAD

**Issue by jkonicki** [vmware-tanzu/tanzu-toolkit-for-visual-studio#17]
Add a confirmation dialog with the user before they permanently delete (+ save this preference as some sort of config)

PT: 175764005

**Comment by atwoosnam** [comment]
Small (9pt):
![image.png](https://images.zenhubusercontent.com/5f6e427c72f8abbfafb30775/592fe01c-64a3-421c-b66e-b38f56f101cf)

Medium (14pt)
![image.png](https://images.zenhubusercontent.com/5f6e427c72f8abbfafb30775/185b16fb-ca0e-48d3-8e72-17e1881bef4c)

Large (24pt)
![image.png](https://images.zenhubusercontent.com/5f6e427c72f8abbfafb30775/971782b5-1a5e-49db-8940-61f7f665a11b)
