### ISSUE TITLE
Null exception when pulling in buildpack options while manifest doesn't have buildpack values

### ISSUE THREAD

**Issue by atwoosnam** [vmware-tanzu/tanzu-toolkit-for-visual-studio#188]
To reproduce, build VSIX & try pushing an app project that has no manifest named "manifest.yaml" or "manifest.yml" in the root directory & do not select a custom manifest.

**Comment by zzori-theoriginal** [comment]
![bperror.PNG](https://images.zenhubusercontent.com/5f86121f98b4ad21fcd4f604/36ac53bc-7f54-4725-85d0-06246bbf7deb)
