### ISSUE TITLE
Refresh Space button does not update app icons

### ISSUE THREAD

**Issue by jkonicki** [vmware-tanzu/tanzu-toolkit-for-visual-studio#19]
PT: 177104430

**Comment by atwoosnam** [comment]
This looks fine now (see demo vid; the icon for `app-1-1-1` changes from green to red to indicate the app has stopped when the space is refreshed independently of the automatic background refresh).

https://images.zenhubusercontent.com/327998348/646d1c30-ac1c-444f-825f-638acff20ef5/refreshspaceupdatesappicons.mp4
