### ISSUE TITLE
Allow feedback submission from within the VS extension

### ISSUE THREAD

**Issue by atwoosnam** [vmware-tanzu/tanzu-toolkit-for-visual-studio#198]
- add button to open default email client?

**Comment by TimHess** [comment]
To which email address? Is there a way to have the email turn into a github issue?

**Comment by ccheetham** [comment]
fwiw ....
https://fire.fundersclub.com/

**Comment by zzori-theoriginal** [comment]
Here's the email to be used for feedback!

![feedbackemailaddy.PNG](https://images.zenhubusercontent.com/5f86121f98b4ad21fcd4f604/607f8775-95cf-4126-9394-3c45a95338f4)

**Comment by zzori-theoriginal** [comment]
okay, now looking into using the System.Process method to open up the default email client when the user tries to send feedback
