### ISSUE TITLE
Deleting an app should delete its associated routes

### ISSUE THREAD

**Issue by atwoosnam** [vmware-tanzu/tanzu-toolkit-for-visual-studio#206]
...otherwise stale routes linger in spaces that no longer contain the apps they were created for.

**Comment by atwoosnam** [comment]
Not that we should use the CF CLI for this, but there *is* a CF CLI option to delete routes along with an app: "`-r`" with `cf delete`
```
$ cf delete -h
NAME:
   delete - Delete an app

USAGE:
   cf.exe delete APP_NAME [-r] [-f]

ALIAS:
   d

OPTIONS:
   -f      Force deletion without confirmation
   -r      Also delete any mapped routes

SEE ALSO:
   apps, scale, stop
```

**Comment by zzori-theoriginal** [comment]
make it a checkbox

**Comment by atwoosnam** [comment]
Deciding (for now?) that in `CloudFoundryService.DeleteAllRoutesForAppAsync`, if any routes fail to delete, we will raise an error but not attempt any retries (to refresh the access token, e.g.). We recognize this is suboptimal but good enough since a prerequisite for deleting routes is making a call to `GetRoutesForAppAsync`, and this method does attempt to refresh stale access tokens. (there's still a chance that routes may not be deleted if the access token expires right after getting all routes for app, but this window feels slim enough not to spend more time engineering for).
