### ISSUE TITLE
Resolve Newtonsoft warning

### ISSUE THREAD

**Issue by atwoosnam** [vmware-tanzu/tanzu-toolkit-for-visual-studio#243]
`The version of Newtonsoft.Json cannot be greater than 9.0.1, but version 12.0.3 is currently being used.	`

**Comment by atwoosnam** [comment]
Found some info in [these docs](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022#modernize-your-vsix-project) on migrating VSIX extensions to Vs2022:

> Some assemblies that aren't unique to the Visual Studio SDK (for example, Newtonsoft.Json.dll) might have been discoverable through a simple <Reference Include="Newtonsoft.Json" /> reference before Visual Studio 2022. But in Visual Studio 2022, they require a package reference instead. The reason is that some Visual Studio runtime and SDK directories have been removed from the default assembly search path in MSBuild.
>
> In switching from direct assembly references to NuGet package references, you might pick up additional assembly references and analyzer packages because NuGet automatically installs the transitive closure of dependencies. This is generally OK, but it might result in additional warnings during your build. Work through these warnings and resolve as many as you can. Consider using in-code #pragma warning disable <id> regions to suppress warnings that you can't resolve.

**Comment by TimHess** [comment]
This issue is specific to VS 2019 and the warning is triggered from `Community.VisualStudio.Toolkit`.

Newtonsoft is used in `CloudFoundryApiClient`. Solutions could include changing that ref to 9.0.1 or switching over to `System.Text.Json`
