### ISSUE TITLE
Error Window UI lift

### ISSUE THREAD

**Issue by atwoosnam** [vmware-tanzu/tanzu-toolkit-for-visual-studio#38]
Our error dialog is very basic at the moment - there's room for improvement in terms of UI.

**Comment by zzori-theoriginal** [comment]
Making these changes that were suggested during IPM:

1. make the window have a fixed position
2. Add a "close" button to replace the red "x" we currently have

**Comment by zzori-theoriginal** [comment]
Had to install 'GalaSoft.MvvmLight' for new 'close' logic
