### ISSUE TITLE
New TAS instances could appear in tree view *automatically* after being added via DeploymentDialog

### ISSUE THREAD

**Issue by atwoosnam** [vmware-tanzu/tanzu-toolkit-for-visual-studio#42]
At the moment, when adding a new connection to a TAS instance via the DeploymentDialog "AddCloud" button, the tree view does not change automatically to add a new "CF Instance" row; seeing the new connection requires a manual refresh (button click).

It should be possible to have these new connections appear automatically the way they do after being added via the CloudExplorerToolWindow's "AddCloud" button.

**Comment by TimHess** [comment]
Only one TAS instance is supported
