### ISSUE TITLE
Improve error messages for when operation errors due to missing target (e.g. deleted app/space/org)

### ISSUE THREAD

**Issue by atwoosnam** [vmware-tanzu/tanzu-toolkit-for-visual-studio#43]
Currently, when using the CloudExplorer to stop/start/delete an app which has been deleted outside the IDE (i.e. the tree view is not in sync with the real CF foundation), an error window is raised with the message "Unable to stop/start/delete {app name}."

This message could be made more explanatory; it could describe that the reason for the error is that the app didn't exist at the time the start/stop command was issued. In the case of an app deletion, we could improve the UX even further and not raise any error when trying to delete an already-deleted app.

**Comment by jkonicki** [comment]
Need to validate the error handling now that we changed to use CFAPI calls.

**Comment by atwoosnam** [comment]
Current error from trying to start a "stale" (i.e. shown in tree view but actually non-existent) app:

**Title:** Encountered an error while starting app 'app-1-1-1'
**Message:** Something went wrong while trying to start app 'app-1-1-1': Response from POST `/v3/apps/2bbeb572-ace9-41c7-983d-74955e8bd2ed/actions/start` was NotFound.

**Comment by zzori-theoriginal** [comment]
- get rid of "something went wrong"
- add in "see logs for more details"

**Comment by zzori-theoriginal** [comment]
![VSerrorpopup.PNG](https://images.zenhubusercontent.com/5f86121f98b4ad21fcd4f604/f6d3ddb6-1003-45e4-8d6b-37375f1b0fa0)
