### ISSUE TITLE
Visual confirmation that Refresh is underway

### ISSUE THREAD

**Issue by atwoosnam** [vmware-tanzu/tanzu-toolkit-for-visual-studio#44]
Currently, when the Refresh button is clicked in the CloudExplorerToolWindow, all app/space/org/cf rows in the tree view will begin to update (i.e. request fresh lists of children behind the scenes), but nothing in the window changes immediately. This might lead some users to question whether or not they initiated the refresh properly.

If a refresh button click were to give some visual confirmation that the refresh process has started but is still ongoing, users will almost certainly have more confidence that they're using the extension properly.

**Comment by jkonicki** [comment]
Duplicate - Addressed in #16
