### ISSUE TITLE
Can't deploy apps to orgs/spaces with spaces in their names

### ISSUE THREAD

**Issue by atwoosnam** [vmware-tanzu/tanzu-toolkit-for-visual-studio#51]
Trying to deploy an app to a space with a space in its name (e.g. "my cool space") results in a failure:
```
Unable to target org 'org-1' or space 'my cool space'.
Space 'my' not found.
```

**Comment by zzori-theoriginal** [comment]
did a run through of pushing an app to both a space and org that contained spaces in their names and it worked! no new code necessary so this story wont have a PR attached. See picture below for instance test:
![spacingapp.PNG](https://images.zenhubusercontent.com/5f86121f98b4ad21fcd4f604/a78c5a73-1505-4521-8674-96ff71e847a3)
