### ISSUE TITLE
Secure the password and any other values that should not be available to the user

### ISSUE THREAD

**Issue by jkonicki** [vmware-tanzu/tanzu-toolkit-for-visual-studio#6]
Login user/pass should be obfuscated.

When calling the CF CLI from the Extension, we should make sure that the password is not exposed anywhere (console output, debug logging, etc)

PT: 176660359

**Comment by atwoosnam** [comment]
We've taken these measures to reduce the risk of exposing a plain text password:
- Password is captured as a `SecureString` from the Login Dialog
- Password is only decoded from a `SecureString` to a readable `string` in the `AuthenticateAsync` method of `CfCliService`
- CF CLI login command does get run with a plaintext version of the password as an argument, but the shell that invokes the command is ephemeral -- it doesn't create a visible window & as far as we can tell, its history is not saved (we haven't found any evidence to be able to know whether or not arguments passed to commands invoked by the `Process` class stick around in system memory after those commands complete, but if they do, they're certainly not easy to find).
- 3 attempts are made to erase the password from system memory after the login command completes:
  1. `passwordStr = null;` (overwrite `string` value for plaintext password)
  2. `password.Clear();` (delete contents of `SecureString`)
  3. `password.Dispose();` (mark `SecureString` as eligible for garbage collection)
