### ISSUE TITLE
Publish our snapshots to a developer feed

### ISSUE THREAD

**Issue by jkonicki** [vmware-tanzu/tanzu-toolkit-for-visual-studio#71]
We should publish our VSIX files to a dev feed for easier access.

**Comment by atwoosnam** [comment]
https://www.youtube.com/watch?v=tLOgsYLJ9q0

**Comment by atwoosnam** [comment]
https://www.vsixgallery.com/extension/TanzuToolkitForVisualStudio.ff7b6f3e-0410-4ff9-a40a-a719ee9da901
