### ISSUE TITLE
As a .NET Framework developer, I can deploy .NET FW apps

### ISSUE THREAD

**Issue by jkonicki** [vmware-tanzu/tanzu-toolkit-for-visual-studio#8]
PT: https://www.pivotaltracker.com/story/show/173963584

**Comment by atwoosnam** [comment]
[These docs](https://docs.cloudfoundry.org/buildpacks/hwc/index.html) describe how to deploy a .NET Framework app using the cf cli. Here's a summary:

#### Prerequisites:

1. Your CF instance is running TASW
2. Your app targets .NET Framework 4.5.1 or later
3. Your app is one of:

    - ASP.NET MVC
    - ASP.NET Web Forms
    - ASP.NET WebAPI Apps
    - Windows Communication Foundation (WCF)

For .NET Console apps or .NET Core apps deploying to Windows, the recommended strategy is to use the [Binary buildpack](https://docs.cloudfoundry.org/buildpacks/binary/index.html) (separate process)

#### HWC configuration
To deploy .NET Framework apps using the HWC buildpack, the app must include a `Web.config` file at its root directory. Most Web.config files work out of the box with CF, with the following constraints:

* Integrated Windows Authentication (IWA) is not yet supported on CF.
* SQL server connection strings must use fully qualified domain names.
* Place connection string values in environment variables or user-provided service instances.

#### Add global error handling (optional but highly recommended)
From the [dotnet cookbook](https://dotnet-cookbook.apps.pcfone.io/intro/getting_started/#application-error-handling):

> To take advantage of the builtin PCF logging your application needs to ‘opt-in’ to ensure you can properly view any unhandled exceptions that may occur in your app. This is a very important step and should be done before pushing the application for the first time. Without a global error handler in place you won’t get any log information back from your application if it crashes on startup.
>
> The easiest way to log any unhandled exceptions is to modify your application’s Global.asax.cs and add a global error handler method that logs to stdout.
> 
> ```
void Application_Error(object sender, EventArgs e)
> {
>     Exception lastError = Server.GetLastError();
>     Console.WriteLine("Unhandled exception: " + lastError.Message + lastError.StackTrace);
> }
```
> If you already have a global exception handler you’ll need to ensure it’s logging to stdout. For example if using a logging framework like log4net you’ll need to configure a console appender so log statements write to stdout.
> 
> For production applications it’s highly recommended to use a configurable logging framework like log4net or NLog instead of writing directly to the Console.
> 
> Once you have added a global error handler you’ll see any unhandled execptions along with their stack trace logged to PCF. You can view the logs in the PCF Apps Manager or from the command line: `cf logs myappname --recent`

#### App deployment

1. Build app
2. From the directory that contains app files & `Web.config`, issue this cf cli command:
`cf push APP-NAME -s windows -b hwc_buildpack`

**Comment by atwoosnam** [comment]
For future reference, here's a list of all properties available on an EnvDTE `Project` (I couldn't find this list in the Microsoft docs but was able to generate it by printing the results of a `foreach (Property prop in proj.Properties)` statement):

```
Properties: 
  WebApplication.AspNetDebugging
  WebApplication.AspnetCompilerIISMetabasePath
  OutputTypeEx
  TargetFrameworkMoniker
  ComVisible
  EnableSecurityDebugging
  OptionCompare
  StartupObject
  WebApplication.SSLEnabled
  WebApplication.UseIIS
  ManifestCertificateThumbprint
  Trademark
  Title
  WebApplication.StartExternalUrl
  WebApplication.IISUrl
  AssemblyOriginatorKeyFileType
  FileName
  WebServer
  AssemblyOriginatorKeyMode
  AssemblyKeyContainerName
  WebApplication.WindowsAuthenticationEnabled
  WebApplication.SecureUrl
  WebApplication.DevelopmentServerCommandLine
  WebApplication.SQLDebugging
  WebApplication.StartPageUrl
  WebApplication.DefaultServerDirectoryListing
  WebApplication.DevelopmentServerVPath
  WebApplication.DevelopmentServerPort
  ProjectType
  ReferencePath
  WebApplication.IsUsingIISExpress
  PreBuildEvent
  WebApplication.AnonymousAuthenticationEnabled
  WebApplication.SilverlightDebugging
  WebApplication.StartCmdLineArguments
  AutoGenerateBindingRedirects
  Copyright
  ApplicationIcon
  WebApplication.CurrentDebugUrl
  ExcludedPermissions
  RunPostBuildEvent
  DefaultTargetSchema
  RootNamespace
  WebApplication.IsUsingCustomServer
  ManifestTimestampUrl
  ManifestKeyFile
  DebugSecurityZoneURL
  Product
  PostBuildEvent
  OptionStrict
  DefaultHTMLPageLayout
  DelaySign
  OutputType
  WebApplication.StartWorkingDirectory
  WebApplication.DebugStartAction
  NeutralResourcesLanguage
  OptionExplicit
  OutputFileName
  ServerExtensionsVersion
  WebApplication.NonSecureUrl
  WebApplication.ToString
  AssemblyGuid
  GenerateManifests
  AssemblyVersion
  Win32ResourceFile
  Description
  URL
  DefaultClientScript
  WebApplication.NativeDebugging
  TargetFramework
  SignManifests
  OfflineURL
  WebServerVersion
  Publish
  AssemblyType
  FullPath
  WebAccessMethod
  WebApplication.UseIISExpress
  WebApplication.BrowseURL
  WebApplication.NTLMAuthentication
  WebApplication.OverrideIISAppRootUrl
  WebApplication.OpenedURL
  AssemblyKeyProviderName
  TypeComplianceDiagnostics
  Company
  ActiveFileSharePath
  AssemblyOriginatorKeyFile
  WebApplication.StartWebServerOnDebug
  WebApplication.AutoAssignPort
  ApplicationManifest
  AssemblyFileVersion
  AspnetVersion
  FileSharePath
  AssemblyName
  WebApplication.EditAndContinue
  WebApplication.ServerDirectoryListing
  LocalPath
  DefaultNamespace
  LinkRepair
  WebApplication.StartExternalProgram
  WebApplication.IISAppRootUrl
  TargetZone
  SignAssembly
```

**Comment by atwoosnam** [comment]
#### ^^ Update ^^

I think C# project properties are documented [here](https://docs.microsoft.com/en-us/dotnet/api/vslangproj165.csharpprojectproperties8?view=visualstudiosdk-2019)... unclear if this is the right reference doc or not (there were several versions of the Project.Properties interface & I tried to grab the latest (8))
