### ISSUE TITLE
Re-authenticate if refresh token is prematurely invalidated

### ISSUE THREAD

**Issue by atwoosnam** [vmware-tanzu/tanzu-toolkit-for-visual-studio#97]
Issue #37 encompasses reauthentication when the CF CLI refresh token expires, but in the event that the refresh token becomes invalid _before_ reaching the end of its prescribed lifetime, this VS extension should be able to recover by reauthenticating to renew the refresh token.

**Comment by jkonicki** [comment]
Related to #37
